BEGIN;
DROP TABLE IF EXISTS inventory_transactions CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS customers CASCADE;

CREATE TABLE customers (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(50) NOT NULL
);
CREATE TABLE categories (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255)
);
CREATE TABLE products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(255),
 description TEXT,
 price DOUBLE PRECISION,
 stock_quantity INTEGER,
 category_id BIGINT REFERENCES categories(id)
);
CREATE TABLE inventory (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id BIGINT NOT NULL UNIQUE REFERENCES products(id),
 quantity INTEGER NOT NULL CHECK (quantity >= 0)
);
CREATE TABLE inventory_transactions (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id BIGINT NOT NULL REFERENCES products(id),
 quantity INTEGER NOT NULL CHECK (quantity > 0),
 type VARCHAR(30) NOT NULL CHECK (type IN ('PURCHASE','SALE','ADJUSTMENT')),
 created_at TIMESTAMP NOT NULL
);
CREATE TABLE carts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id BIGINT NOT NULL UNIQUE REFERENCES customers(id)
);
CREATE TABLE cart_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
 product_id BIGINT NOT NULL REFERENCES products(id),
 quantity INTEGER NOT NULL CHECK (quantity > 0),
 CONSTRAINT uq_cart_product UNIQUE(cart_id,product_id)
);
CREATE TABLE orders (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id BIGINT NOT NULL REFERENCES customers(id),
 status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','SHIPPED','DELIVERED','CANCELLED')),
 total_amount DOUBLE PRECISION NOT NULL CHECK (total_amount >= 0)
);
CREATE TABLE order_items (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
 product_id BIGINT NOT NULL REFERENCES products(id),
 quantity INTEGER NOT NULL CHECK (quantity > 0),
 price DOUBLE PRECISION NOT NULL CHECK (price >= 0)
);
CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_inventory_transactions_product_id ON inventory_transactions(product_id);
CREATE INDEX idx_inventory_transactions_created_at ON inventory_transactions(created_at);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX idx_cart_items_product_id ON cart_items(product_id);
COMMIT;
